<a href="https://colab.research.google.com/github/mitalimishra24/Mini-Project/blob/main/Mini_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Library Imports

import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize
import pandas as pd

### ***DATA GATHERING*** 



In [ ]:
cd /content/drive/MyDrive/Images

/content/drive/MyDrive/Images


In [ ]:
#Importing Data from Drive 
DATA = '/content/drive/MyDrive/Images'

### **DATA PREPROCESSING**

In [ ]:
Category = ['dog','fish','butterfly']
target = []
images = []
flat_data =[]
for i in Category:

  #Label Encoding for Category of Images
  class_num = Category.index(i)
  path = os.path.join(DATA,i)
  print(path)
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img))
    
    #Data Normalization
    # 0-255 will be normalized 0-1
    img_resized = resize(img_array,(150,150,3)) 

    #Flattening of Data 
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_num)

flat_data  = np.array(flat_data)
target = np.array(target)
images = np.array(images)

/content/drive/MyDrive/Images/dog
/content/drive/MyDrive/Images/fish
/content/drive/MyDrive/Images/butterfly


In [ ]:
#Data Frame Creation

df = pd.DataFrame(flat_data)
df

0         1         2      ...     67497     67498     67499
0   0.286085  0.274320  0.144908  ...  0.498291  0.435546  0.307114
1   0.664544  0.676309  0.703130  ...  0.885658  0.708325  0.546048
2   0.168627  0.188235  0.203922  ...  0.327542  0.327542  0.347150
3   0.338013  0.365464  0.100076  ...  0.052013  0.075762  0.021399
4   0.481176  0.419255  0.320392  ...  0.305020  0.332471  0.168118
5   0.376209  0.403660  0.333072  ...  0.255856  0.393111  0.651935
6   0.817388  0.620952  0.495305  ...  0.497383  0.521506  0.556573
7   0.392673  0.306667  0.216337  ...  0.371562  0.274284  0.230611
8   0.309300  0.471134  0.182222  ...  0.417631  0.354886  0.303906
9   0.103373  0.189647  0.035515  ...  0.479504  0.440903  0.397608
10  0.595098  0.653922  0.736275  ...  0.302876  0.295882  0.254706
11  0.000000  0.136000  0.237020  ...  0.039426  0.116916  0.183583
12  0.992157  0.992157  0.992157  ...  0.983333  0.983333  0.983333
13  0.098039  0.137255  0.043137  ...  0.220562  0.230124  0.137967
14  0.827624  0.808016  0.796029  ...  0.171497  0.227804  0.079987
15  0.051208  0.015914  0.027678  ...  0.000000  0.000000  0.000000
16  0.277180  0.214614  0.151331  ...  0.511190  0.444523  0.334719
17  0.992157  0.992157  0.992157  ...  0.979093  0.967328  0.939877
18  0.323186  0.459578  0.076294  ...  0.491255  0.604000  0.334392
19  0.982409  0.822954  0.611190  ...  0.613281  0.476026  0.349464
20  0.128533  0.140732  0.069699  ...  0.711248  0.662219  0.230291
21  0.435490  0.420431  0.556588  ...  0.114327  0.076092  0.104523
22  0.160784  0.207422  0.151255  ...  0.558108  0.470441  0.099304
23  0.013255  0.263608  0.472980  ...  0.000000  0.313725  0.460706
24  0.117268  0.070588  0.066667  ...  0.108824  0.080392  0.071569
25  0.665833  0.985020  0.934131  ...  0.262141  0.605928  0.455278
26  0.000000  0.371333  0.486588  ...  0.190157  0.205333  0.110784
27  0.007843  0.007843  0.007843  ...  0.980716  0.993794  0.978745
28  0.188235  0.219608  0.294118  ...  0.430379  0.516654  0.508810
29  0.231542  0.474680  0.384484  ...  0.163556  0.212830  0.143137
30  0.332549  0.296830  0.473301  ...  0.221569  0.085719  0.144739
31  0.324131  0.395931  0.486268  ...  0.378967  0.611330  0.580078
32  0.175268  0.533333  0.737255  ...  0.081150  0.115974  0.190484
33  0.000000  0.000000  0.000000  ...  0.658322  0.679258  0.635712
34  0.075922  0.347020  0.478759  ...  0.204305  0.456161  0.512278
35  0.341046  0.330948  0.295654  ...  0.693170  0.600719  0.524542
36  0.020824  0.623765  0.604157  ...  0.191980  0.551843  0.601183
37  0.959804  0.984641  0.001961  ...  0.093791  0.232026  0.000654
38  0.003922  0.168627  0.329412  ...  0.022693  0.129412  0.226902
39  0.019608  0.250980  0.643137  ...  0.779242  0.701908  0.513647
40  0.577333  0.502824  0.236157  ...  0.394922  0.418853  0.198784
41  0.345098  0.576471  0.630392  ...  0.382353  0.544118  0.313725
42  0.635856  0.726052  0.655464  ...  0.420170  0.561346  0.373111
43  0.141176  0.650980  0.015686  ...  0.525712  0.332078  0.440196
44  0.454902  0.517647  0.270588  ...  0.320092  0.310451  0.126056
45  0.956686  0.988637  0.964529  ...  0.348745  0.357971  0.329539
46  0.346771  0.135987  0.128144  ...  0.064431  0.064431  0.065830
47  0.303948  0.480418  0.217673  ...  0.526680  0.645268  0.321778
48  0.289451  0.378667  0.144353  ...  0.150180  0.216114  0.065010
49  0.141176  0.650980  0.015686  ...  0.525712  0.332078  0.440196
50  0.133895  0.149196  0.089778  ...  0.720510  0.823627  0.665993
51  0.988235  0.988235  0.988235  ...  0.988235  0.988235  0.988235
52  0.363072  0.668954  0.193268  ...  0.410327  0.686209  0.205033
53  0.131373  0.244637  0.436275  ...  0.296039  0.262745  0.525490
54  0.037464  0.063830  0.038497  ...  0.151190  0.152275  0.152575
55  0.400000  0.423174  0.148664  ...  0.610850  0.578246  0.399961
56  0.526471  0.750000  0.589216  ...  0.583268  0.757778  0.737288
57  0.480471  0.685961  0.411451  ...  0.362353  0.490290  0.21

In [ ]:
#Adding Target as our new column

df['Target'] = target
df

0         1         2  ...     67498     67499  Target
0   0.286085  0.274320  0.144908  ...  0.435546  0.307114       0
1   0.664544  0.676309  0.703130  ...  0.708325  0.546048       0
2   0.168627  0.188235  0.203922  ...  0.327542  0.347150       0
3   0.338013  0.365464  0.100076  ...  0.075762  0.021399       0
4   0.481176  0.419255  0.320392  ...  0.332471  0.168118       0
5   0.376209  0.403660  0.333072  ...  0.393111  0.651935       0
6   0.817388  0.620952  0.495305  ...  0.521506  0.556573       0
7   0.392673  0.306667  0.216337  ...  0.274284  0.230611       0
8   0.309300  0.471134  0.182222  ...  0.354886  0.303906       0
9   0.103373  0.189647  0.035515  ...  0.440903  0.397608       0
10  0.595098  0.653922  0.736275  ...  0.295882  0.254706       0
11  0.000000  0.136000  0.237020  ...  0.116916  0.183583       0
12  0.992157  0.992157  0.992157  ...  0.983333  0.983333       0
13  0.098039  0.137255  0.043137  ...  0.230124  0.137967       0
14  0.827624  0.808016  0.796029  ...  0.227804  0.079987       0
15  0.051208  0.015914  0.027678  ...  0.000000  0.000000       0
16  0.277180  0.214614  0.151331  ...  0.444523  0.334719       0
17  0.992157  0.992157  0.992157  ...  0.967328  0.939877       0
18  0.323186  0.459578  0.076294  ...  0.604000  0.334392       0
19  0.982409  0.822954  0.611190  ...  0.476026  0.349464       0
20  0.128533  0.140732  0.069699  ...  0.662219  0.230291       1
21  0.435490  0.420431  0.556588  ...  0.076092  0.104523       1
22  0.160784  0.207422  0.151255  ...  0.470441  0.099304       1
23  0.013255  0.263608  0.472980  ...  0.313725  0.460706       1
24  0.117268  0.070588  0.066667  ...  0.080392  0.071569       1
25  0.665833  0.985020  0.934131  ...  0.605928  0.455278       1
26  0.000000  0.371333  0.486588  ...  0.205333  0.110784       1
27  0.007843  0.007843  0.007843  ...  0.993794  0.978745       1
28  0.188235  0.219608  0.294118  ...  0.516654  0.508810       1
29  0.231542  0.474680  0.384484  ...  0.212830  0.143137       1
30  0.332549  0.296830  0.473301  ...  0.085719  0.144739       1
31  0.324131  0.395931  0.486268  ...  0.611330  0.580078       1
32  0.175268  0.533333  0.737255  ...  0.115974  0.190484       1
33  0.000000  0.000000  0.000000  ...  0.679258  0.635712       1
34  0.075922  0.347020  0.478759  ...  0.456161  0.512278       1
35  0.341046  0.330948  0.295654  ...  0.600719  0.524542       1
36  0.020824  0.623765  0.604157  ...  0.551843  0.601183       1
37  0.959804  0.984641  0.001961  ...  0.232026  0.000654       1
38  0.003922  0.168627  0.329412  ...  0.129412  0.226902       1
39  0.019608  0.250980  0.643137  ...  0.701908  0.513647       1
40  0.577333  0.502824  0.236157  ...  0.418853  0.198784       2
41  0.345098  0.576471  0.630392  ...  0.544118  0.313725       2
42  0.635856  0.726052  0.655464  ...  0.561346  0.373111       2
43  0.141176  0.650980  0.015686  ...  0.332078  0.440196       2
44  0.454902  0.517647  0.270588  ...  0.310451  0.126056       2
45  0.956686  0.988637  0.964529  ...  0.357971  0.329539       2
46  0.346771  0.135987  0.128144  ...  0.064431  0.065830       2
47  0.303948  0.480418  0.217673  ...  0.645268  0.321778       2
48  0.289451  0.378667  0.144353  ...  0.216114  0.065010       2
49  0.141176  0.650980  0.015686  ...  0.332078  0.440196       2
50  0.133895  0.149196  0.089778  ...  0.823627  0.665993       2
51  0.988235  0.988235  0.988235  ...  0.988235  0.988235       2
52  0.363072  0.668954  0.193268  ...  0.686209  0.205033       2
53  0.131373  0.244637  0.436275  ...  0.262745  0.525490       2
54  0.037464  0.063830  0.038497  ...  0.152275  0.152575       2
55  0.400000  0.423174  0.148664  ...  0.578246  0.399961       2
56  0.526471  0.750000  0.589216  ...  0.757778  0.737288       2
57  0.480471  0.685961  0.411451  ...  0.490290  0.214086       2
58  0.477264  0.527882  0.438993  ...  0.564370  0.485939       2
59  0.564706  0.528366  0.533333  ...  0.370267  0.

### **APPLYING SVM ALGORITHM**

In [ ]:
#Splitting the DataFrame into Testing And Training

x = df.iloc[:,:67500]
y = df.iloc[:,67500]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0)

In [ ]:
#Importing libraries for SVM Algorithm and Applying GridSearch CV

from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

svm_classifier = SVC()

parameters = [{'C':[1,10,100,1000],'kernel': ['linear'],
               'C':[1,10,100,1000],'kernel': ['rbf'],'gamma':[0.0,0.001,0.1,10,20,100],
               'C':[1,10,100,1000],'kernel': ['rbf'],'gamma':['scale']}]
grid_search = GridSearchCV(estimator =svm_classifier,param_grid = parameters,scoring='accuracy',cv=10)
grid_search = grid_search.fit(x_train,y_train)

In [ ]:
grid_search.best_score_

0.545

In [ ]:
grid_search.best_params_

{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}

In [ ]:
from sklearn.svm import SVC

model = SVC(C=10,gamma='scale',kernel='rbf')
model.fit(x_train,y_train)

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 0, 1, 1, 0, 1, 2, 2, 2, 0, 0, 1, 0, 1])

### **EVALUATION METRICS**

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

#Accuracy Score
print('ACCURACY SCORE : ',accuracy_score(y_pred,y_test)*100)

ACCURACY SCORE :  66.66666666666666


In [ ]:
#Confusion Matrix

print('CONFUSION MATRIX \n',confusion_matrix(y_pred,y_test))

CONFUSION MATRIX 
 [[3 1 2]
 [1 5 0]
 [0 1 2]]


In [ ]:
#Classification Report

print('CLASSIFICATION REPORT \n',classification_report(y_pred,y_test))

CLASSIFICATION REPORT 
               precision    recall  f1-score   support

           0       0.75      0.50      0.60         6
           1       0.71      0.83      0.77         6
           2       0.50      0.67      0.57         3

    accuracy                           0.67        15
   macro avg       0.65      0.67      0.65        15
weighted avg       0.69      0.67      0.66        15



### **PREDICTING FOR RANDOM IMAGES**

In [ ]:
#Using images URL for predicting results for random Images

flat_data1 = []
url = input('Enter your URL')
img = imread(url)
img_resized = resize(img_array,(150,150,3))
flat_data1.append(img_resized.flatten())
flat_data1 = np.array(flat_data1)
Result = model.predict(flat_data1)
Result = Category[Result[0]]
print(Result)

Enter your URLhttps://www.thesprucepets.com/thmb/sfuyyLvyUx636_Oq3Fw5_mt-PIc=/3760x2820/smart/filters:no_upscale()/adorable-white-pomeranian-puppy-spitz-921029690-5c8be25d46e0fb000172effe.jpg
dog
